command: ['streamlit', 'run', 'app.py']
env:
  - name: WAREHOUSE_ID
    valueFrom: sql_warehouse
  - name: HISTORY_TABLE
    valueFrom: history_table
  - name: FORECAST_TABLE
    valueFrom: forecast_table
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: 'false'
